FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Khadamat Api

Khadamat app is a simple app.



## Group Init

Resources related to init in the API.

## init [/init]

A init object has the following attributes:

### View a init Detail [GET]

+ Response 200 (application/json)

        {
          "descriptions":[
            
            "takafol": {
              "title": "title",
              "details": "detais"
            },
            "re3aya": {
              "title": "title",
              "details":"details"
            },
            "sadakat": {
              "title": "title",
              "details":"details"
            }
            
          ]
        }
        
## Group Descriptions

Resources related to description in the API.

## descriptions [/modereyet/desc/{type}]

A description object has the following attributes:

+ type

+ Parameters
    + type (required, string`) ... type of the descriptions in form of a string --> "re3aya, sadakat, takafol"

### View a description Detail [GET]

+ Response 200 (application/json)

        {
          "title": "title",
          "details": "detais"
        }

## Group Library

Resources related to library in the API.

## Library [/library/{type}/page/{page}/itemsPerPage/{itemsPerPage}]

A Library object has the following attributes:

+ id
+ title
+ url

+ Parameters
    + type (required, string`) ... type of the library in form of a string --> "Friday, Most or Ramadan"
    + page (required, int`) ... page of the library in form of an integer --> 1, 2 ...
    + itemsPerPage (required, int`) ... number of items in the page in an integer form --> 10, 20, ...

### View a Library Detail [GET]

+ Response 200 (application/json)

                [
                    {
                      "id": 2,
                      "title": "خطبة الجمعة ",
                      "date": "2015-12-04",
                      "url": "dsfgsdgsdfsdf sdf"
                    },
                    {
                      "id": 2,
                      "title": "خطبة الجمعة ",
                      "date": "2015-12-04",
                      "url": "dsfgsdgsdfsdf sdf"
                    },
                    {
                      "id": 2,
                      "title": "خطبة الجمعة ",
                      "date": "2015-12-04",
                      "url": "dsfgsdgsdfsdf sdf"
                    },
                    {
                      "id": 2,
                      "title": "خطبة الجمعة ",
                      "date": "2015-12-04",
                      "url": "dsfgsdgsdfsdf sdf"
                    },
                    {
                      "id": 2,
                      "title": "خطبة الجمعة ",
                      "date": "2015-12-04",
                      "url": "dsfgsdgsdfsdf sdf"
                    }
                ]

## Occasion [/occasion/{todayDate}/itemsPerPage/{itemsPerPage}]

+ Parameters
    + todayDate (required, string, `"2015-12-04"`) ... start date of occasions
    + itemsPerPage (required, int`) ... number of items in the page in an integer form --> 10, 20, ...

### Get the occasion list [GET]

This action allows you to get the occasions between two dates.

+ Response 201

              [
                    {
                      "id": 2,
                      "title": "title",
                      "details": " ...................",
                      "dateHejre": "...........",
                      "dateMilede": "2015-12-04",
                      "url": "dsfgsdgsdfsdf sdf"
                    },
                    {
                      "id": 2,
                      "title": "title",
                      "details": " ...................",
                      "dateHejre": "...........",
                      "dateMilede": "2015-12-04",
                      "url": "dsfgsdgsdfsdf sdf"
                    },
                    {
                      "id": 2,
                      "title": "title",
                      "details": " ...................",
                      "dateHejre": "...........",
                      "dateMilede": "2015-12-04",
                      "url": "dsfgsdgsdfsdf sdf"
                    },
                     {
                      "id": 2,
                      "title": "title",
                      "details": " ...................",
                      "dateHejre": "...........",
                      "dateMilede": "2015-12-04",
                      "url": "dsfgsdgsdfsdf sdf"
                    },
                     {
                      "id": 2,
                      "title": "title",
                      "details": " ...................",
                      "dateHejre": "...........",
                      "dateMilede": "2015-12-04",
                      "url": "dsfgsdgsdfsdf sdf"
                    },
                     {
                      "id": 2,
                      "title": "title",
                      "details": " ...................",
                      "dateHejre": "...........",
                      "dateMilede": "2015-12-04",
                      "url": "dsfgsdgsdfsdf sdf"
                    }
                ]

## News Collection [/news/page/{page}/itemsPerPage/{itemsPerPage}]

+ Parameters
    + page (required, int`) ... page of the library in form of a string --> 1, 2 ...
    + itemsPerPage (required, int`) ... page of the library in form of a string --> 10, 20, ...

### List All News [GET]

+ Response 200 (application/json)

    + Headers

            Link: </news/page/1/itemsPerPage/10>; rel="next"

    + Body

            [
                {
                  "id": 2,
                  "title": "عنوان الخبر " ,
                  "date": "2015-12-04",
                  "details": "ونقلت وكاستشار الزعيم الإيراني آية الله علي خامنئي كايهان "  ,
                  "url": "dsfgsdgsdfsdf sdf"
                },
                {
                  "id": 2,
                  "title": "عنوان الخبر " ,
                  "date": "2015-12-04",
                  "details": "ونقلت وكاستشار الزعيم الإيراني آية الله علي خامنئي كايهان "  ,
                  "url": "dsfgsdgsdfsdf sdf"
                },
                {
                  "id": 2,
                  "title": "عنوان الخبر " ,
                  "date": "2015-12-04",
                  "details": "ونقلت وكاستشار الزعيم الإيراني آية الله علي خامنئي كايهان "  ,
                  "url": "dsfgsdgsdfsdf sdf"
                },
                {
                  "id": 2,
                  "title": "عنوان الخبر " ,
                  "date": "2015-12-04",
                  "details": "ونقلت وكاستشار الزعيم الإيراني آية الله علي خامنئي كايهان "  ,
                  "url": "dsfgsdgsdfsdf sdf"
                },
                {
                  "id": 2,
                  "title": "عنوان الخبر " ,
                  "date": "2015-12-04",
                  "details": "ونقلت وكاستشار الزعيم الإيراني آية الله علي خامنئي كايهان "  ,
                  "url": "dsfgsdgsdfsdf sdf"
                }
            ]


# Group Basmet 5eir
allow to ebsom bel 5eir

## basmet 5eir [/basmet/5eir]
### Login [POST]
+ Request (application/json)

        {
          "name": "jaafrrrr",
          "phone": "5498132",
          "code": "961",
          "helpType": "Madeye" ,
          "profitWho": "ايتام "
        }

+ Response 200 (application/json)

        {
          "success": true,
          "error": 0,
          "message": "",
          "data": null
        }

