FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Khadamat Api

Khadamat app is a simple app.



## Group Init

Resources related to init in the API.

## init [/init]

A init object has the following attributes:

### View a init Detail [GET]

+ Response 200 (application/json)

        {
            "takafolDesc":{
                "title": "title",
                "details": "details",
                "types": "types details"
            },
            "re3ayaDesc":{
                "title": "title",
                "details":"details"
            },
            "sadakatDesc":{
                "title": "title",
                "details":"details"
            },
            "kijat5ayreyen":{
                "how": "text",
                "contactUs": "text",
                "mawared": "لبيلي يبليب ل يبل"
            },
            "kijatReznama":{
                "how": "text",
                "contactUs": "ليبليبليب يبل يب",
                "mawared": "gdfلأ][ليبليبل"
            },
            "sandouk":{
                "how": "text",
                "contactUs": "text",
                "mawared": "text"
            },
            "halat":{
                "year": 2015,
                "nAytam": 452,
                "nFo2ara": 456,
                "n3ajaza": 8946,
                "nMo3awaken": 851
            },
            "takdimat":{
                "year": 2015,
                "mose3adet_nakdeye": 4528562,
                "mawed_8eze2eye_7osas": 945241,
                "mose3adet_so7eye": 7843,
                "it3am_iftarat":3245,
                "ada7e_lo7omat": 6215,
                "mose3adet_3edeyet_aytam": 6122,
                "keswet_3ed_aytem": 6125,
                "zaket_fotra": 1564,
                "total": 6311
            },
            "anwa3TasdedAlkafala":[
                {
                    "id": 1,
                    "name": "شهري"
                },
                {
                    "id": 2,
                    "name": "فصلي"
                },
                {
                    "id": 3,
                    "name": "سنوي"
                }
            ],
            "anwa3MaleyetAlkafala":[
                {
                    "id": 1,
                    "name": "sadakat"
                }
            ],
            "tawasalMa3ana":{
                "address": "Beirut",
                "telephone": "0982323",
                "whatsapp": "098743",
                "facebook": "facebook.com/page",
                "email": "test@test.com"
            },
            "de3ayeet":[
                {
                    "id": 1,
                    "title": "ad title",
                    "text": "text for advertisement1"
                },
                {
                    "id": 1,
                    "title": "ad title",
                    "text": "text for advertisement2"
                }
            ],
            "mawake3":[
                {
                    "id": 1,
                    "longitude": 35.49547940,
                    "latitude": 33.88862890,
                    "Name": "بيروت",
                    "Details": ""
                },
                {
                    "id": 1,
                    "longitude": 35.505746899999960,
                    "latitude": 33.89329880,
                    "Name": "سيتي سينتير",
                    "Details": ""
                }
            ]
        }
        

## Group Library

Resources related to library in the API.

## Library [/library/{type}/page/{page}/itemsPerPage/{itemsPerPage}]

A Library object has the following attributes:

+ id
+ title
+ url

+ Parameters
    + type (required, string`) ... type of the library in form of a string --> "Friday, Most or Ramadan"
    + page (required, int`) ... page of the library in form of an integer --> 1, 2 ...
    + itemsPerPage (required, int`) ... number of items in the page in an integer form --> 10, 20, ...

### View a Library Detail [GET]

+ Response 200 (application/json)

                [
                    {
                      "id": 2,
                      "title": "خطبة الجمعة ",
                      "date": "2015-12-04",
                      "url": "http://demos.thesoftwareguy.in/jplayer-demo/travis.mp3"
                    },
                    {
                      "id": 2,
                      "title": "خطبة الجمعة ",
                      "date": "2015-12-04",
                      "url": "http://demos.thesoftwareguy.in/jplayer-demo/travis.mp3"
                    },
                    {
                      "id": 2,
                      "title": "خطبة الجمعة ",
                      "date": "2015-12-04",
                      "url": "http://demos.thesoftwareguy.in/jplayer-demo/travis.mp3"
                    },
                    {
                      "id": 2,
                      "title": "خطبة الجمعة ",
                      "date": "2015-12-04",
                      "url": "http://demos.thesoftwareguy.in/jplayer-demo/travis.mp3"
                    },
                    {
                      "id": 2,
                      "title": "خطبة الجمعة ",
                      "date": "2015-12-04",
                      "url": "http://demos.thesoftwareguy.in/jplayer-demo/travis.mp3"
                    }
                ]

## Occasion [/occasion/itemsPerPage/{itemsPerPage}]

+ Parameters
    + itemsPerPage (required, int`) ... number of items in the page in an integer form --> 10, 20, ...

### Get the occasion list [GET]

This action allows you to get the occasions after the current date.

+ Response 201

              [
                    {
                      "id": 2,
                      "title": "title",
                      "details": " ...................",
                      "dateHejre": "...........",
                      "dateMilede": "2015-12-04",
                      "url": "http://farm4.static.flickr.com/3516/3758038002_6377014a0d.jpg"
                    },
                    {
                      "id": 2,
                      "title": "title",
                      "details": " ...................",
                      "dateHejre": "...........",
                      "dateMilede": "2015-12-04",
                      "url": "http://farm4.static.flickr.com/3516/3758038002_6377014a0d.jpg"
                    },
                    {
                      "id": 2,
                      "title": "title",
                      "details": " ...................",
                      "dateHejre": "...........",
                      "dateMilede": "2015-12-04",
                      "url": "http://farm4.static.flickr.com/3516/3758038002_6377014a0d.jpg"
                    },
                     {
                      "id": 2,
                      "title": "title",
                      "details": " ...................",
                      "dateHejre": "...........",
                      "dateMilede": "2015-12-04",
                      "url": "http://farm4.static.flickr.com/3516/3758038002_6377014a0d.jpg"
                    },
                     {
                      "id": 2,
                      "title": "title",
                      "details": " ...................",
                      "dateHejre": "...........",
                      "dateMilede": "2015-12-04",
                      "url": "http://farm4.static.flickr.com/3516/3758038002_6377014a0d.jpg"
                    },
                     {
                      "id": 2,
                      "title": "title",
                      "details": " ...................",
                      "dateHejre": "...........",
                      "dateMilede": "2015-12-04",
                      "url": "http://farm4.static.flickr.com/3516/3758038002_6377014a0d.jpg"
                    }
                ]

## News Collection [/news/page/{page}/itemsPerPage/{itemsPerPage}]

+ Parameters
    + page (required, int`) ... page of the library in form of a int --> 1, 2 ...
    + itemsPerPage (required, int`) ... n items of the library in form of a int --> 10, 20, ...

### List All News [GET]

+ Response 200 (application/json)

    + Headers

            Link: </news/page/1/itemsPerPage/10>; rel="next"

    + Body

            [
                {
                  "id": 2,
                  "title": "عنوان الخبر " ,
                  "date": "2015-12-04",
                  "details": "ونقلت وكاستشار الزعيم الإيراني آية الله علي خامنئي كايهان "  ,
                  "url": "http://www.mtgdnews.com/wp-content/uploads/news-4.jpg"
                },
                {
                  "id": 2,
                  "title": "عنوان الخبر " ,
                  "date": "2015-12-04",
                  "details": "ونقلت وكاستشار الزعيم الإيراني آية الله علي خامنئي كايهان "  ,
                  "url": "http://www.mtgdnews.com/wp-content/uploads/news-4.jpg"
                },
                {
                  "id": 2,
                  "title": "عنوان الخبر " ,
                  "date": "2015-12-04",
                  "details": "ونقلت وكاستشار الزعيم الإيراني آية الله علي خامنئي كايهان "  ,
                  "url": "http://www.mtgdnews.com/wp-content/uploads/news-4.jpg"
                },
                {
                  "id": 2,
                  "title": "عنوان الخبر " ,
                  "date": "2015-12-04",
                  "details": "ونقلت وكاستشار الزعيم الإيراني آية الله علي خامنئي كايهان "  ,
                  "url": "http://www.mtgdnews.com/wp-content/uploads/news-4.jpg"
                },
                {
                  "id": 2,
                  "title": "عنوان الخبر " ,
                  "date": "2015-12-04",
                  "details": "ونقلت وكاستشار الزعيم الإيراني آية الله علي خامنئي كايهان "  ,
                  "url": "http://www.mtgdnews.com/wp-content/uploads/news-4.jpg"
                }
            ]


# Group Basmet 5eir
allow to ebsom bel 5eir

## basmet 5eir [/basmet/5eir]
### Basmet 5eir [POST]

1    ايتام
2    فقراء
3    معوقين
4    عجزة
------------------
1    مساعدة ماديّة
2    مساعدة عينيّة
+ Request (application/json)

        {
            "caseId": 1, \\ 0 is random case.
            "name": "jaafrrrr",
            "phone": "5498132",
            "code": "961",
            "helpType": 1,
            "profitWho": 1
        }

+ Response 200 (application/json)

        {
          "success": true,
          "error": 0,
          "message": "",
          "data": null
        }
        
        
# Group Aytam
allow get the aytam list

## aytam list [/aytam/list/page/{page}/itemsPerPage/{itemsPerPage}]

+ Parameters
    + page (required, int`) ... page of the aytam in form of a int --> 1, 2 ...
    + itemsPerPage (required, int`) ... n items of the aytam in form of a int --> 10, 20, ...

### Aytam list [POST]

+ Response 200 (application/json)

        [
          {
            "id": 2,
            "name": "ali",
            "age": 15,
            "details": "dsdsdsdsdd",
            "url": "http://fc07.deviantart.net/fs71/f/2012/327/9/d/kid_stock_by_gooooman-d5lvqm7.jpg"
          },
          {
            "id": 3,
            "name": "ali",
            "age": 15,
            "details": "dsdsdsdsdd",
            "url": "http://fc07.deviantart.net/fs71/f/2012/327/9/d/kid_stock_by_gooooman-d5lvqm7.jpg"
          },
          {
            "id": 4,
            "name": "ali",
            "age": 15,
            "details": "dsdsdsdsdd",
            "url": "http://fc07.deviantart.net/fs71/f/2012/327/9/d/kid_stock_by_gooooman-d5lvqm7.jpg"
          },
          {
            "id": 5,
            "name": "ali",
            "age": 15,
            "details": "dsdsdsdsdd",
            "url": "http://fc07.deviantart.net/fs71/f/2012/327/9/d/kid_stock_by_gooooman-d5lvqm7.jpg"
          },
          {
            "id": 6,
            "name": "ali",
            "age": 15,
            "details": "dsdsdsdsdd",
            "url": "http://fc07.deviantart.net/fs71/f/2012/327/9/d/kid_stock_by_gooooman-d5lvqm7.jpg"
          },
          {
            "id": 7,
            "name": "ali",
            "age": 15,
            "details": "dsdsdsdsdd",
            "url": "http://fc07.deviantart.net/fs71/f/2012/327/9/d/kid_stock_by_gooooman-d5lvqm7.jpg"
          },
          {
            "id": 8,
            "name": "ali",
            "age": 15,
            "details": "dsdsdsdsdd",
            "url": "http://fc07.deviantart.net/fs71/f/2012/327/9/d/kid_stock_by_gooooman-d5lvqm7.jpg"
          },
          {
            "id": 9,
            "name": "ali",
            "age": 15,
            "details": "dsdsdsdsdd",
            "url": "http://fc07.deviantart.net/fs71/f/2012/327/9/d/kid_stock_by_gooooman-d5lvqm7.jpg"
          }
        ]


# Group ResponserShip
allow to send the data of a responser ship

## ResponserShip [/responsership]
### ResponserShip [POST]
+ Request (application/json)

        {
          "name": "etst",
          "phoneNumber": "45215452",
          "phoneCode": "00961",
          "kimatKafala": 452645,
          "kafalaPeriod": 24,
          "tasdidKafala": 2,
          "maleyetkafala": 1,
          "typeKafala": "معوق",
          "quantity": 5,
          "yatimId" : 0 // if zero so the typeKafala is not "يتيم"
        }

+ Response 200 (application/json)

        {
          "success": true,
          "error": 0,
          "message": "",
          "data": null
        }
      
        
# Group Social Case
allow receive the data for the social cases

## social case [/social/case]
### SocialCase [GET]

+ Response 200 (application/json)

        {
          "id": 2,
          "title": "this is a title",
          "details": "test ...........................rtefefef",
          "medias":[
            "http://www.aihcp.org/blog/wp-content/uploads/2012/07/shutterstock_32557234.jpg",
            "http://www.ebookfrenzy.com/android_book/movie.mp4",
            "http://www.ebookfrenzy.com/android_book/movie.mp4",
            "http://www.aihcp.org/blog/wp-content/uploads/2012/07/shutterstock_32557234.jpg"
            ]
        }
        
        
# Group Library Count
allows the addition of the count concerning the library file

## library counter [/library/addToCount/{fileId}]

+ Parameters
    + fileId (required, int`) ... id of the file that was downloaded or listened to --> 1, 2 ...


### LibraryAdd [GET]

+ Response 200 (application/json)

        {
          "success": true,
          "error": 0,
          "message": "",
          "data": null
        }
        
        
        
# Group Registrations
register device
        
## tokenRegister [/tokenRegister]
### Registering the device token [POST]

                 
+ Request (application/json)

            {   "deviceToken": "123456ergerg", 
                "deviceType": "android"}

+ Response 202 (application/json)

    + Headers

            Location: api/tokenRegister

    + Body

            {
                "success": true,
                "error": 0,
                "message": "",
                "data": ""
            }

      
        
        
